### ISSUE TITLE
Members list

### ISSUE THREAD

**Issue by sebd11** [Les-Ingenieuses-de-l-ETS/ingenieuses.etsmtl.ca#20]
- liste des membres actuels (avec rôle si applicable)
- liste des membres retraités

**Comment by fredefortin** [comment]
Fichier avec tous les membres selon les années : https://docs.google.com/spreadsheets/d/1zVYuRkoz38mIxVmICrjEFum-OMCAU7gJr_6iwqXzG5c/edit#gid=0
